### ISSUE TITLE
TODO: Fix history

### ISSUE THREAD

**Issue by thomasvt1** [thomasvt1/MemeBot#11]
`[2019-06-11 22:52:46]: ERROR Unhandled rejection: TypeError: client.math.calculateInvestmentReturn is not a function 
TypeError: client.math.calculateInvestmentReturn is not a function
    at Object.exports.run (c:\Users\thoma\OneDrive\Documents\Reddit\MemeBot\commands\history.js:37:44)`

Since math.js changed
https://github.com/thomasvt1/MemeBot/blob/78e521b5a072e4c1b678f7af2e24d871860899e1/modules/math.js#L69

This call is no longer working
https://github.com/thomasvt1/MemeBot/blob/78e521b5a072e4c1b678f7af2e24d871860899e1/commands/history.js#L37

**Comment by Keanu73** [comment]
Easy fix.
