### ISSUE TITLE
OAuth2 verification guild structure?

### ISSUE THREAD

**Issue by Keanu73** [thomasvt1/MemeBot#2]
Maybe assign users a role once they're verified that can be set?

**Comment by thomasvt1** [comment]
I'm still trying to figure out what the purpose would be of user roles, and what the added benefits are.

**Comment by Keanu73** [comment]
I think user roles don't have much purpose other than for firm discord servers, where they structure the roles by mapping it to the firm roles. I was thinking of making a seperate Reddit OAuth2 verification bot for this purpose, but now I'm wondering, we could maybe integrate this functionality into MemeBot....

**Comment by Keanu73** [comment]
Until we can figure out an actual purpose for this sort of thing, the issue is closed until further notice.
